fix: compatibility with pre-commit ansible-lint (#51)
I have a pre-commit hook that uses ansible-lint, which in turn uses `ansible-config dump` behind the scenes.

This hardcoded locale setting makes it fail with:

    ERROR: Ansible requires the locale encoding to be UTF-8; Detected None.

Thus, setting the UTF-8 mode, which is more similar to what every distro ships these days by default.

@moduon MT-1075