Release Ver. 2.2.0 (#74)
* minor fix required (#42)

* updates

* fix-for - 	modified:   ansible_collections/lvrfrc87/git_acp/plugins/module_utils/git_actions.py

* fix-for - 	modified:   ansible_collections/lvrfrc87/git_acp/tests/integration/targets/git_acp/tasks/main.yml

* Release V. 1.0.4 (#43)

* fix sanity tests; update changelog' add poetry

* add warning message for ssh_params with https mode

* work on integration tests

* fix warning message; update integration tests

* add package for Ver 1.0.4

* Bump ansible from 2.10.7 to 4.2.0 (#45)

Bumps [ansible](https://github.com/ansible/ansible) from 2.10.7 to 4.2.0.
- [Release notes](https://github.com/ansible/ansible/releases)
- [Commits](https://github.com/ansible/ansible/commits)

---
updated-dependencies:
- dependency-name: ansible
  dependency-type: direct:production
...

Signed-off-by: dependabot[bot] <support@github.com>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Update set_url logic

* rebase with master

* Fix spelling

* Fix spelling in error message

* remove else statement

* fix sanity tests

* Fixed typo in README.md (#52)

* fix: compatibility with pre-commit ansible-lint (#51)

I have a pre-commit hook that uses ansible-lint, which in turn uses `ansible-config dump` behind the scenes.

This hardcoded locale setting makes it fail with:

    ERROR: Ansible requires the locale encoding to be UTF-8; Detected None.

Thus, setting the UTF-8 mode, which is more similar to what every distro ships these days by default.

@moduon MT-1075

* feat(pull): allow pulling before pushing (#53)

* feat(pull): allow pulling before pushing

When running several tasks in parallel in forks of the same remote, it is normal that one of them fails.

With this new feature, you can instruct the module to pull upstream changes before pushing. It's also easy to use Ansible's loop-until feature to make several attempts until one succeeds.

@moduon MT-1075

* tests(pull): add case

* Bump cryptography from 37.0.2 to 39.0.1 (#55)

Bumps [cryptography](https://github.com/pyca/cryptography) from 37.0.2 to 39.0.1.
- [Release notes](https://github.com/pyca/cryptography/releases)
- [Changelog](https://github.com/pyca/cryptography/blob/main/CHANGELOG.rst)
- [Commits](https://github.com/pyca/cryptography/compare/37.0.2...39.0.1)

---
updated-dependencies:
- dependency-name: cryptography
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Version 1.5.0

* Bump markdown-it-py from 2.1.0 to 2.2.0 (#59)

Bumps [markdown-it-py](https://github.com/executablebooks/markdown-it-py) from 2.1.0 to 2.2.0.
- [Release notes](https://github.com/executablebooks/markdown-it-py/releases)
- [Changelog](https://github.com/executablebooks/markdown-it-py/blob/master/CHANGELOG.md)
- [Commits](https://github.com/executablebooks/markdown-it-py/compare/v2.1.0...v2.2.0)

---
updated-dependencies:
- dependency-name: markdown-it-py
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Update module args for git_config (#57)

* Update module args for git_config

* Update mode in git_config

* remove git_config, remote, user and token

* Release v. 2.0.0

* Fix #63 (#64)

* Update to version 2.1.0

* Use same return method as pull

* Add support for explicit push

* Update CHANGELOG for 2.1.0

* Update to version 2.1.0

* Upate deployment script

* Use AnsibleModule dependencies instead

* Fix doc string for . Update return for commit

* Fix typos for description

* Fix typos for description

* Fix typos for description

---------

Co-authored-by: tom0010 <@tom0010>

* Ver 2.1.0 release (#65)

* update tests

* commit save

* Update test

* invert vars position in git push

* Update docs

* Update changelog

* Update DOCUMENTATION

* Update README.md

* add 2.1.0 release

* Ver. 2.2.0 (#73)

* update tests

* commit save

* Update test

* invert vars position in git push

* Update docs

* Update changelog

* Update DOCUMENTATION

* Update README.md

* commit save

* commit save

* add git clean functionality

* Add package

* remove clean.yml

* Update changelog

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: lj020326 <lj020326@users.noreply.github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Thomas Bridge <thomasbridge74@users.noreply.github.com>
Co-authored-by: Jairo Llopis <973709+yajo@users.noreply.github.com>
Co-authored-by: tom0010 <41154665+tom0010@users.noreply.github.com>